<a href="https://colab.research.google.com/github/adikul25/Notebooks/blob/main/FrozenLake.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
pip install gym -q

In [2]:
import numpy as np
import gym
import random
import time
from IPython.display import clear_output

In [3]:
env = gym.make("FrozenLake-v1")

/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py:283: DeprecationWarning: `should_run_async` will not call `transform_cell` automatically in the future. Please pass the result to `transformed_cell` argument and any exception that happen during thetransform in `preprocessing_exc_tuple` in IPython 7.17 and above.
  and should_run_async(code)
/usr/local/lib/python3.10/dist-packages/gym/core.py:317: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/usr/local/lib/python3.10/dist-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(


In [5]:
action_size = env.action_space.n
state_size = env.observation_space.n

In [6]:
qtable = np.zeros((state_size, action_size))
print(qtable)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [7]:
total_episodes = 10000        # Total episodes
learning_rate = 0.2          # Learning rate
max_steps = 99                # Max steps per episode
gamma = 0.99                 # Discounting rate

# Exploration parameters
epsilon = 1.0                 # Exploration rate
max_epsilon = 1.0             # Exploration probability at start
min_epsilon = 0.01            # Minimum exploration probability
decay_rate = 0.001

In [8]:
rewards = []

# 2 For life or until learning is stopped
for episode in range(total_episodes):
    # Reset the environment
    state = env.reset()
    #step = 0
    done = False
    total_rewards = 0

    for step in range(max_steps):
        # 3. Choose an action a in the current world state (s)
        ## First we randomize a number
        exp_exp_tradeoff = random.uniform(0, 1)

        ## If this number > greater than epsilon --> exploitation (taking the biggest Q value for this state)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])

        # Else doing a random choice --> exploration
        else:
            action = env.action_space.sample()

        # Take the action (a) and observe the outcome state(s') and reward (r)
        new_state, reward, done, info = env.step(action)

        # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]
        # qtable[new_state,:] : all the actions we can take from new state
        qtable[state, action] = qtable[state, action] * (1-learning_rate) + learning_rate * (reward + gamma * np.max(qtable[new_state, :]))

        state = new_state
        total_rewards += reward

        # Our new state is state


        # If done (if we're dead) : finish episode
        if done == True:
            break

    # Reduce epsilon (because we need less and less exploration)
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)

#Calculate abd print the average reward per thousand episodes

rewards_per_thousand_episodes = np.split(np.array(rewards), total_episodes/1000)
# count = 1000
# print('***********Average reward per thousand episodes*************\n')
# for r in rewards_per_thousand_episodes:
#   print(count, ":", str(sum(r/1000)))
#   count +=1000

print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.5066
[[0.50252162 0.48715505 0.47676674 0.47727202]
 [0.42052189 0.26260527 0.37990078 0.47273934]
 [0.39363043 0.38231616 0.36196696 0.44720908]
 [0.20555254 0.37880417 0.2807076  0.43685309]
 [0.51700345 0.33018421 0.37507017 0.43192919]
 [0.         0.         0.         0.        ]
 [0.31900934 0.06419389 0.07098489 0.0552436 ]
 [0.         0.         0.         0.        ]
 [0.45616396 0.43738453 0.32623807 0.55807091]
 [0.52568294 0.58425911 0.45554816 0.3825987 ]
 [0.53301446 0.22990545 0.35823404 0.34605094]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.45532857 0.45749213 0.70161948 0.40341571]
 [0.68990684 0.90013082 0.79373454 0.73416227]
 [0.         0.         0.         0.        ]]


In [ ]:
import gym
env = gym.make("FrozenLake-v1")
env.reset()

for episode in range(5):
    state = env.reset()
    #step = 0
    done = False
    #print("****************************************************")
    print("EPISODE ", episode+1)
    time.sleep(1)

    for step in range(max_steps):
        clear_output(wait=True)
        env.render()
        time.sleep(0.3)


        # Take the action (index) that have the maximum expected future reward given that state
        action = np.argmax(qtable[state,:])

        new_state, reward, done, info = env.step(action)

        if done:
            clear_output(wait=True)
            # Here, we decide to only print the last state (to see if our agent is on the goal or fall into an hole)
            env.render()
            if reward == 1:
                print("We reached our Goal 🏆")
                time.sleep(3)
            else:
                print("We fell into a hole ☠️")
                time.sleep(3)
            clear_output(wait=True)

            # We print the number of step it took.
            #print("Number of steps", step)

            break
        state = new_state
env.close()

EPISODE  4
